
'use client';

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Loader2 } from 'lucide-react';
import Image from 'next/image';

interface InfographicDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  imageUrl: string | null;
  isGenerating: boolean;
  drugName: string;
}

export default function InfographicDialog({
  open,
  onOpenChange,
  imageUrl,
  isGenerating,
  drugName,
}: InfographicDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl h-[90vh]">
        <DialogHeader>
          <DialogTitle>AI-Generated Infographic for {drugName}</DialogTitle>
          <DialogDescription>
            This is a visual summary generated by AI. You can right-click the image to save it.
          </DialogDescription>
        </DialogHeader>
        <div className="flex items-center justify-center h-full w-full rounded-lg border border-dashed">
          {isGenerating ? (
            <div className="flex flex-col items-center gap-4 text-muted-foreground">
              <Loader2 className="h-12 w-12 animate-spin text-primary" />
              <p>Generating your infographic... This may take a moment.</p>
            </div>
          ) : imageUrl ? (
            <div className="relative w-full h-full">
              <Image
                src={imageUrl}
                alt={`Infographic for ${drugName}`}
                fill
                style={{ objectFit: 'contain' }}
              />
            </div>
          ) : (
            <p className="text-muted-foreground">No infographic to display.</p>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
